name = "einmana"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改

#id = "6cfb5f134e634163a9e7b76460e70f60"				#KV数据库id

